Changes and alterations
ChromeGaming/Chrome-Gaming-Certification pull request #14
Opened 2024-06-19 20:14 UTC by kshandilaya

I took the liberty to add some div and using those to re-design the css of the page.

Added a background image also provided better ui to the form section.

![WhatsApp Image 2024-06-20 at 01 41 19_55c3a68b](https://github.com/ChromeGaming/Chrome-Gaming-Certification/assets/172832884/32a9b100-3e51-46a3-997e-0daca84b0679)

2024-06-19 20:17 UTC, kshandilaya commented
Please do share your response.

2024-06-20 12:50 UTC, Durgesh4993 reviewed
Resolve conflicts

2024-06-20 15:53 UTC, kshandilaya commented
Accept the code it is running properly I just added some divs in the html and rest I changed the css for whole.

![IMG_20240620_010741.jpg](https://github.com/ChromeGaming/Chrome-Gaming-Certification/assets/172832884/6bb26da1-cdcf-43b8-8e01-cbc6f0d4bfca)

2024-12-21 05:50 UTC, GautamAnjali569 reviewed
Ok

2024-12-21 05:50 UTC, GautamAnjali569 requested changes
Resolve Conflicts

2025-09-17 14:13 UTC, closed without merging